"""
Configuration module for AI BI Streamlit Reports.
Loads environment variables and provides application settings.
"""
import os
from pathlib import Path
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# Base paths
BASE_DIR = Path(__file__).parent
DATA_DIR = BASE_DIR / "data"
OUTPUT_DIR = BASE_DIR / os.getenv("OUTPUT_DIR", "media/output")

# Ensure directories exist
DATA_DIR.mkdir(exist_ok=True)
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

# API Keys (optional)
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY", "")
GOOGLE_API_KEY = os.getenv("GOOGLE_API_KEY", "")
APPS_SCRIPT_WEBHOOK_URL = os.getenv("APPS_SCRIPT_WEBHOOK_URL", "")

# Data generation settings
RANDOM_SEED = 42
NUM_CUSTOMERS = 1000  # Increased to 1000 for comprehensive dataset
ORDERS_PER_CUSTOMER_MIN = 3
ORDERS_PER_CUSTOMER_MAX = 5
DATA_DAYS_BACK = 180

# Customer segments
SEGMENTS = ["new", "returning", "vip", "at_risk"]
SEGMENT_DISTRIBUTION = {
    "new": 0.25,
    "returning": 0.30,
    "vip": 0.25,
    "at_risk": 0.20
}

# Product categories
PRODUCT_CATEGORIES = [
    "fitness", "electronics", "books", "home_decor", 
    "wellness", "travel", "gaming", "education"
]

# Order channels
ORDER_CHANNELS = ["web", "app", "store"]

# Interest pool
INTEREST_POOL = [
    "fitness", "electronics", "books", "home_decor",
    "wellness", "travel", "gaming", "education"
]

# Buying behavior types
BUYING_BEHAVIORS = ["impulse_buyer", "researcher", "bargain_hunter", "loyal", "seasonal"]

# Pain points for targeting
PAIN_POINTS_POOL = [
    "budget_conscious", "time_constrained", "quality_focused",
    "convenience_seeker", "eco_conscious", "tech_savvy",
    "price_sensitive", "brand_loyal", "novelty_seeker"
]

# Preferred contact times
CONTACT_TIMES = ["morning", "afternoon", "evening", "weekend"]

# Video settings
VIDEO_RESOLUTION = (1280, 720)
VIDEO_FPS = 24
VIDEO_DURATION_RANGE = (15, 30)

# TTS settings
TTS_ENGINE = "pyttsx3"  # or "gtts"
TTS_RATE = 150  # words per minute for pyttsx3

# Image generation settings
AI_IMAGE_SIZE = "1024x1024"
AI_IMAGE_PROMPT_TEMPLATE = (
    "Create an abstract, professional business intelligence themed image "
    "representing a {segment} customer interested in {interests}. "
    "Use modern, clean design with data visualization elements."
)

# Email template
EMAIL_TEMPLATE = """
<!DOCTYPE html>
<html>
<head>
    <style>
        body {{ font-family: Arial, sans-serif; line-height: 1.6; color: #333; }}
        .container {{ max-width: 600px; margin: 0 auto; padding: 20px; }}
        .header {{ background: #0066cc; color: white; padding: 20px; text-align: center; }}
        .kpi-grid {{ display: grid; grid-template-columns: 1fr 1fr; gap: 15px; margin: 20px 0; }}
        .kpi-card {{ background: #f5f5f5; padding: 15px; border-radius: 5px; }}
        .kpi-value {{ font-size: 24px; font-weight: bold; color: #0066cc; }}
        .kpi-label {{ font-size: 14px; color: #666; }}
        .footer {{ text-align: center; margin-top: 30px; color: #666; font-size: 12px; }}
        .button {{ display: inline-block; padding: 10px 20px; background: #0066cc; color: white; text-decoration: none; border-radius: 5px; margin: 10px 5px; }}
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>Weekly BI Report</h1>
            <p>Automated Business Intelligence Summary</p>
        </div>
        
        <h2>Hi {name},</h2>
        <p>Here's your weekly business intelligence summary:</p>
        
        <div class="kpi-grid">
            <div class="kpi-card">
                <div class="kpi-value">₹{total_spend:.0f}</div>
                <div class="kpi-label">Total Spend</div>
            </div>
            <div class="kpi-card">
                <div class="kpi-value">{orders_count}</div>
                <div class="kpi-label">Orders Placed</div>
            </div>
            <div class="kpi-card">
                <div class="kpi-value">₹{aov:.0f}</div>
                <div class="kpi-label">Average Order Value</div>
            </div>
            <div class="kpi-card">
                <div class="kpi-value">{top_category}</div>
                <div class="kpi-label">Top Category</div>
            </div>
        </div>
        
        <p><strong>Segment:</strong> {segment}</p>
        <p><strong>Order Frequency:</strong> {frequency:.1f} orders/month</p>
        
        <div style="text-align: center; margin: 30px 0;">
            {video_link}
            {charts_link}
        </div>
        
        <div class="footer">
            <p>This is an automated report generated by AI BI Streamlit Reports</p>
            <p>&copy; 2024 AI BI System. All rights reserved.</p>
        </div>
    </div>
</body>
</html>
"""

def get_customer_output_dir(customer_id: str) -> Path:
    """Get the output directory for a specific customer."""
    customer_dir = OUTPUT_DIR / customer_id
    customer_dir.mkdir(parents=True, exist_ok=True)
    return customer_dir

def get_customer_subdirs(customer_id: str) -> dict:
    """Get all subdirectories for a customer's outputs."""
    base = get_customer_output_dir(customer_id)
    subdirs = {
        'charts': base / 'charts',
        'audio': base / 'audio',
        'images': base / 'images',
        'video': base / 'video'
    }
    for subdir in subdirs.values():
        subdir.mkdir(parents=True, exist_ok=True)
    return subdirs
